language: node_js
git:
  submodules: false
cache:
  yarn: true
  npm: true
before_install:
  - npm i -g npm@6.7.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn global add codacy-coverage
script: yarn test-with-coverage