export default [
  { value: 'string', display: '\'string\'' },
  { value: Number.NEGATIVE_INFINITY, display: 'Number.NEGATIVE_INFINITY' },
  { value: Number.POSITIVE_INFINITY, display: 'Number.POSITIVE_INFINITY' },
  { value: Number.NaN, display: 'Number.NaN' },
  { value: 0, display: '0' },
  { value: 1, display: '1' },
  { value: 0.1, display: '0.1' },
  { value: -1, display: '-1' },
  { value: -0.1, display: '-0.1' },
  { value: undefined, display: 'undefined' },
  { value: null, display: 'null' },
  { value: false, display: 'false' },
  { value: true, display: 'true' },
  { value: {}, display: '{}' },
  { value: [], display: '[]' },
  { value: new Date(), display: 'new Date()' },
  { value: Boolean, display: 'Boolean' },
  { value: String, display: 'String' },
  { value: Number, display: 'Number' },
  { value: Object, display: 'Object' },
  { value: Array, display: 'Array' },
  { value: Date, display: 'Date' }
]